### ISSUE TITLE
WrkzCoin v0.2.14 Test Log

### ISSUE THREAD

**Issue by wrkzdev** [wrkzcoin/wrkzcoin#12]
WrkzCoin Test Log
Build from: https://github.com/wrkzcoin/wrkzcoin/tree/dev

Binaries for Testing:
Windows: [wrkzcoin-dd8fa0705d96f26315d4415294895a015f7ae147-windows.zip](https://github.com/wrkzcoin/wrkzcoin/files/3904784/wrkzcoin-dd8fa0705d96f26315d4415294895a015f7ae147-windows.zip)
Linux: [wrkzcoin-dd8fa0705d96f26315d4415294895a015f7ae147-linux.tar.gz](https://github.com/wrkzcoin/wrkzcoin/files/3904787/wrkzcoin-dd8fa0705d96f26315d4415294895a015f7ae147-linux.tar.gz)
AARCH64: [wrkzcoin-dd8fa0705d96f26315d4415294895a015f7ae147-aarch64.tar.gz](https://github.com/wrkzcoin/wrkzcoin/files/3904791/wrkzcoin-dd8fa0705d96f26315d4415294895a015f7ae147-aarch64.tar.gz)
MacOS: [wrkzcoin-dd8fa0705d96f26315d4415294895a015f7ae147-macos.tar.gz](https://github.com/wrkzcoin/wrkzcoin/files/3906537/wrkzcoin-dd8fa0705d96f26315d4415294895a015f7ae147-macos.tar.gz)

### Wrkzd Tests
- Daemon connects to local DB
  - [x] Windows
  - [x] Linux
  - [x] AARCH64
  - [x] MacOS
- Local DB does not require resync
  - [x] Windows
  - [x] Linux
  - [x] AARCH64
  - [ ] MacOS
- Peer ID assigned
  - [x] Windows
  - [x] Linux
  - [x] AARCH64
  - [x] MacOS
- Connections to multiple peers are made
  - [x] Windows
  - [x] Linux
  - [x] AARCH64
  - [x] MacOS
- Daemon able to sync with external checkpoints
  - [x] Windows
  - [x] Linux
  - [ ] AARCH64
  - [ ] MacOS
- Daemon able to sync without external checkpoints
  - [x] Windows
  - [x] Linux
  - [ ] AARCH64
  - [x] MacOS
- Daemon able to sync from 0 with external checkpoints
  - [x] Windows
  - [x] Linux
  - [ ] AARCH64
  - [ ] MacOS
- Daemon able to sync from 0 without external checkpoints
  - [x] Windows
  - [x] Linux
  - [ ] AARCH64
  - [x] MacOS
- Daemon stays synchronized for 24 hours
  - [x] Windows
  - [x] Linux
  - [ ] AARCH64
  - [ ] MacOS

### zedwallet/beta Tests
- Connect to local daemon
  - [x] Windows
  - [x] Linux
  - [ ] AARCH64
  - [x] MacOS
- Connect to a remote daemon
  - [x] Windows
  - [x] Linux
  - [ ] AARCH64
  - [x] MacOS
- Send a transaction
  - [x] Windows
  - [x] Linux
  - [ ] AARCH64
  - [x] MacOS
- Receive a transaction
  - [x] Windows
  - [x] Linux
  - [ ] AARCH64
  - [x] MacOS
- Perform a fusion transaction
  - [x] Windows
  - [x] Linux
  - [ ] AARCH64
  - [x] MacOS
- Export keys and seeds
  - [x] Windows
  - [x] Linux
  - [ ] AARCH64
  - [x] MacOS
- Import from keys and seeds correctly
  - [x] Windows
  - [x] Linux
  - [ ] AARCH64
  - [x] MacOS
- Perform a full reset
  - [x] Windows
  - [x] Linux
  - [ ] AARCH64
  - [ ] MacOS
- Integrated Addresses work
  - [x] Windows
  - [x] Linux
  - [ ] AARCH64
  - [x] MacOS
- Scan From Height Works Correctly
  - [x] Windows
  - [x] Linux
  - [ ] AARCH64
  - [x] MacOS

### wrkz-service Tests
- Connect to local daemon
  - [ ] Windows
  - [ ] Linux
  - [ ] AARCH64
  - [ ] MacOS
- Connect to a remote daemon
  - [ ] Windows
  - [ ] Linux
  - [ ] AARCH64
  - [ ] MacOS
- Send a transaction
  - [ ] Windows
  - [ ] Linux
  - [ ] AARCH64
  - [ ] MacOS
- Receive a transaction
  - [ ] Windows
  - [ ] Linux
  - [ ] AARCH64
  - [ ] MacOS
- Perform a fusion transaction
  - [ ] Windows
  - [ ] Linux
  - [ ] AARCH64
  - [ ] MacOS
- Export keys and seeds
  - [ ] Windows
  - [ ] Linux
  - [ ] AARCH64
  - [ ] MacOS
- Import from keys and seeds correctly
  - [ ] Windows
  - [ ] Linux
  - [ ] AARCH64
  - [ ] MacOS
- Perform a full reset
  - [ ] Windows
  - [ ] Linux
  - [ ] AARCH64
  - [ ] MacOS
- Integrated Addresses work
  - [ ] Windows
  - [ ] Linux
  - [ ] AARCH64
  - [ ] MacOS
- All RPC endpoints and methods are operational
  - [ ] Windows
  - [ ] Linux
  - [ ] AARCH64
  - [ ] MacOS
- Scan From Height Works Correctly
  - [ ] Windows
  - [ ] Linux
  - [ ] AARCH64
  - [ ] MacOS

**Comment by wrkzdev** [comment]
Just added mac binary.

**Comment by old-greywolf** [comment]
## System Info:

<b>OS Used for Tests:</b>  Windows 10 Pro, Version 1903, OS build 18362.476
<b>OS Used for Tests:</b>  Ubuntu 18.10 Linux 4.18.0-25-generic
<b>OS Used for Tests:</b>  macOS Catalina, Version 10.15
<b>as of:</b>  23:00 PST, 11/29/19

### Wrkzd Tests

Daemon connects to local DB
- [x] Windows
- [x] Linux
- [ ] MacOS

Local DB does not require resync
- [ ] Windows
- [x] Linux
- [ ] MacOS

Peer ID assigned
- [x] Windows
- [x] Linux
- [ ] MacOS

Connections to multiple peers are made
- [x] Windows
- [x] Linux
- [ ] MacOS

Daemon able to sync with external checkpoints
- [ ] Windows
- [ ] Linux
- [ ] MacOS

Daemon able to sync without external checkpoints
- [ ] Windows
- [x] Linux
- [ ] MacOS

Daemon able to sync from 0 with external checkpoints
- [ ] Windows
- [x] Linux
- [ ] MacOS

Daemon able to sync from 0 without external checkpoints
- [ ] Windows
- [ ] Linux
- [ ] MacOS

Daemon stays synchronized for 24 hours
- [ ] Windows
- [ ] Linux
- [ ] MacOS

### zedwallet Tests

Connect to local daemon
- [ ] Windows
- [x] Linux
- [ ] MacOS

Connect to remote daemon
- [ ] Windows
- [ ] Linux
- [ ] MacOS

Send a transaction

- [ ] Windows
- [x] Linux
- [ ] MacOS

Receive a transaction

- [ ] Windows
- [x] Linux
- [ ] MacOS

Perform a fusion transaction

- [ ] Windows
- [x] Linux
- [ ] MacOS

Export keys and seeds

- [ ] Windows
- [x] Linux
- [ ] MacOS

Import from keys and seeds correctly

- [ ] Windows
- [ ] Linux
- [ ] MacOS

Perform a full reset

- [ ] Windows
- [ ] Linux **(in progress)**
- [ ] MacOS

Integrated Addresses work

- [ ] Windows
- [x] Linux
- [ ] MacOS

Scan From Height Works Correctly

- [ ] Windows
- [x] Linux
- [ ] MacOS

### zedwallet-beta Tests

Connect to local daemon

- [ ] Windows
- [x] Linux
- [ ] MacOS

Connect to remote daemon

- [ ] Windows
- [ ] Linux
- [ ] MacOS

Send a transaction

- [ ] Windows
- [ ] Linux
- [ ] MacOS

Receive a transaction

- [ ] Windows
- [ ] Linux
- [ ] MacOS

Perform a fusion transaction

- [ ] Windows
- [ ] Linux
- [ ] MacOS

Export keys and seeds

- [ ] Windows
- [ ] Linux
- [ ] MacOS

Import from keys and seeds correctly

- [ ] Windows
- [ ] Linux
- [ ] MacOS

Perform a full reset

- [ ] Windows
- [ ] Linux
- [ ] MacOS

Integrated Addresses work

- [ ] Windows
- [ ] Linux
- [ ] MacOS

Scan From Height Works Correctly

- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by old-greywolf** [comment]
## System Info:

<b>OS Used for Tests:</b>  Windows 10 Pro, Version 1903, OS build 18362.476
<b>OS Used for Tests:</b>  Ubuntu 18.10 Linux 4.18.0-25-generic
<b>OS Used for Tests:</b>  macOS Catalina, Version 10.15
<b>as of:</b>  19:10 PST, 12/03/19

**ALL TESTS COMPLETE**

### Wrkzd Tests

Daemon connects to local DB
- [x] Windows
- [x] Linux
- [x] MacOS

Local DB does not require resync
- [x] Windows
- [x] Linux
- [x] MacOS

Peer ID assigned
- [x] Windows
- [x] Linux
- [x] MacOS

Connections to multiple peers are made
- [x] Windows
- [x] Linux
- [x] MacOS

Daemon able to sync with external checkpoints
- [x] Windows
- [x] Linux
- [x] MacOS

Daemon able to sync without external checkpoints
- [x] Windows
- [x] Linux
- [x] MacOS

Daemon able to sync from 0 with external checkpoints
- [x] Windows
- [x] Linux
- [x] MacOS

Daemon able to sync from 0 without external checkpoints
- [x] Windows
- [x] Linux
- [x] MacOS

Daemon stays synchronized for 24 hours
- [x] Windows
- [x] Linux
- [x] MacOS

### zedwallet Tests

Connect to local daemon
- [x] Windows
- [x] Linux
- [x] MacOS

Connect to remote daemon
- [x] Windows
- [x] Linux
- [x] MacOS

Send a transaction

- [x] Windows
- [x] Linux
- [x] MacOS

Receive a transaction

- [x] Windows
- [x] Linux
- [x] MacOS

Perform a fusion transaction

- [x] Windows
- [x] Linux
- [x] MacOS

Export keys and seeds

- [x] Windows
- [x] Linux
- [x] MacOS

Import from keys and seeds correctly

- [x] Windows
- [x] Linux
- [x] MacOS

Perform a full reset

- [x] Windows
- [x] Linux
- [x] MacOS

Integrated Addresses work

- [x] Windows
- [x] Linux
- [x] MacOS

Scan From Height Works Correctly

- [x] Windows
- [x] Linux
- [x] MacOS

### zedwallet-beta Tests

Connect to local daemon

- [x] Windows
- [x] Linux
- [x] MacOS

Connect to remote daemon

- [x] Windows
- [x] Linux
- [x] MacOS

Send a transaction

- [x] Windows
- [x] Linux
- [x] MacOS

Receive a transaction

- [x] Windows
- [x] Linux
- [x] MacOS

Perform a fusion transaction

- [x] Windows
- [x] Linux
- [x] MacOS

Export keys and seeds

- [x] Windows
- [x] Linux
- [x] MacOS

Import from keys and seeds correctly

- [x] Windows
- [x] Linux
- [x] MacOS

Perform a full reset

- [x] Windows
- [x] Linux
- [x] MacOS

Integrated Addresses work

- [x] Windows
- [x] Linux
- [x] MacOS

Scan From Height Works Correctly

- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by wrkzdev** [comment]
Tyvm for testing @old-greywolf :)
