### ISSUE TITLE
ZSTD compression and sync speed

### ISSUE THREAD

**Issue by wrkzdev** [wrkzcoin/wrkzcoin#4]
I have tested three daemons below to explore how zstd could reduce the data dir size. Here are the summary:

| Daemon | Height    | No compression         | With zstd compression |
|--------|-----------|------------------------|-----------------------|
| DEGO   | 1,401,822 | 129G data/DB 182G data | 87G data/DB & 140G data |
| TRTL   | 1,779,752 |  56G data/DB 76G data  |  38G data/DB & 58G data |
| WRKZ   |   602,575 |  14G data/DB 18G data  | 8.8G data/DB & 13G data |

And result of zedwallet-beta sync. I tested with WRKZ daemon only:
**(a)** Default daemon without compression.
**(b)** Daemon with zstd compression build (no rocksdb params adjusted).

### Cases and steps of running in sequences:

** _Step 1: Daemon WRKZ **(b)** with zstd compression is currently running_ **
* Case 1) Daemon **(b)** with zstd | 30,403 tx | zedwallet-beta (default thread 8)

** _Step 2: Shutdown WRKZ daemon **(b)**, start new daemon **(a)** with existing different data dir without compression_ **

* Case 2) Daemon **(a)** no zstd | 30,403 tx | zedwallet-beta (default thread 8)
* Case 3) Daemon **(a)** no zstd | Empty Wallet | zedwallet-beta (default thread 8)
* Case 4) Daemon **(a)** no zstd | 30,403 tx | zedwallet-beta (default thread 8)

** _Step 3: Shutdown WRKZ daemon **(a)**, start new daemon **(b)** with existing different data dir with zstd compression_ **

* Case 5) Daemon **(b)** with zstd | 30,408 tx | zedwallet-beta (default thread 8)
* Case 6) Daemon **(b)** with zstd | Empty Wallet | zedwallet-beta (default thread 8)
* Case 7) Daemon **(b)** with zstd | 30,412 tx | zedwallet-beta (default thread 8)

### Case 1 to case 7 in summary table:

| Case   	| Num. Blocks 	| Duration 	| Wallet tx    	| Blocks/s 	|
|--------	|-------------	|----------	|--------------	|----------	|
| Case 1 	|   601,456   	| 51mn40s  	| 30,403 tx    	|    194   	|
| Case 2 	|   601,631   	| 1h14mn   	| 30,403 tx    	|    134   	|
| Case 3 	|   601,658   	| 19mn50s  	| Empty Wallet 	|    505   	|
| Case 4 	|   601,707   	| 53mn     	| 30,403 tx    	|    189   	|
| Case 5 	|   601,818   	| 1h38mn   	| 30,408 tx    	|    102   	|
| Case 6 	|   601,838   	| 19mn10s  	| Empty Wallet 	|    523   	|
| Case 7 	|   601,894   	| 51mn     	| 30,412 tx    	|    196   	|

### Let's compare case 2) with 5); 3) with 6) and 4) with 7) and summary:
* Case 2) and 5) First time when daemon just started, a wallet sync from 0 take longer time. One with compression take even longer time comparing to one without compression.
* Case 3) and 6) Empty wallet is fast for both cases. With or without compression, it is still at higher speed.
* Case 4) and 7)  result not much different after we have either case 2) or case 5) run.

**Comment by bobbieltd** [comment]
In file included from /data/src/wrkzcoin2/external/rocksdb/options/cf_options.h:14:0,
                 from /data/src/wrkzcoin2/external/rocksdb/db/builder.h:13,
                 from /data/src/wrkzcoin2/external/rocksdb/db/builder.cc:10:
/data/src/wrkzcoin2/external/rocksdb/util/compression.h:38:10: fatal error: zstd.h: No such file or directory
 #include <zstd.h>
          ^~~~~~~~
compilation terminated.

**Comment by wrkzdev** [comment]
I also encountered this, and it was fixed before I pushed to dev branch. That shall be fixed already. Did you clone from dev branch? Did you encounter any error or warning during cmake?

I tested to clone and re-compiled again from dev branch, it's OK.

**Comment by bobbieltd** [comment]
Dev branch. Anyone else tested to compile ? Maybe, you installed zstd and it finds zstd.h at include directory from system (outside) not from zstd in wrkzcoin directory.

**Comment by wrkzdev** [comment]
@bobbieltd Can you check if this one fixed?
https://github.com/wrkzcoin/wrkzcoin/commit/468d1513f574bc21b0b3d27c66f9560cc4fdf770

**Comment by bobbieltd** [comment]
Cool, it complies now. I lost 1 hour yesterday to fix it but unsuccessful hehe. Good !

**Comment by wrkzdev** [comment]
default compression will be enabled by default next release with zstd :)
